version: 0.1.0
USER_AGENT: 'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1)'

# database
MYSQL_HOST: 'localhost'
MYSQL_DATABASE: 'mydatabase'
MYSQL_USER: 'root'
MYSQL_PASSWORD: 'mypassword'


# telegram
API_TOKEN: '5117169385:AAEMJp6qWx3-a4B_FxlJ1WiWf8v3qA87Ojc'